# hpa (HorizontalPodAutoscaler)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sorteos-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sorteos-app
  minReplicas: 2    # Mínimo de réplicas requerido
  maxReplicas: 5    # Máximo de réplicas permitido
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # Escalar al alcanzar 60% de CPU utilizada