apiVersion: v1
kind: Service
metadata:
  name: sorteos-service
spec:
  type: LoadBalancer    # Establezco el tipo LoadBalancer
  ports:
    - port: 80          # Puerto expuesto externamente
      targetPort: 3000  # Puerto de la aplicación
      protocol: TCP
  selector:
    app: sorteos-app
